import { GetAllRentalsResponse } from "./types/bike.types"

export const bRes: GetAllRentalsResponse = {
  data: {
    items: [
      {
        category: "BIKE",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 1,
        name: "Mountain Explorer X1",
        status: true,
      },
      {
        category: "BIKE",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 2,
        name: "Mountain Explorer X2",
        status: true,
      },
      {
        category: "SCOOTER",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 3,
        name: "Honda Dio",
        status: true,
      },
      {
        category: "SCOOTER",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 4,
        name: "Honda Dio",
        status: false,
      },
      {
        category: "SCOOTER",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 5,
        name: "Honda Dio",
        status: false,
      },
      {
        category: "BIKE",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 6,
        name: "Mountain Explorer X1",
        status: true,
      },
      {
        category: "BIKE",
        description: "A high-performance mountain bike for rugged trails.",
        hourlyRate: 15.5,
        id: 7,
        name: "Ather 250",
        status: true,
      },
      {
        category: "BIKE",
        description: null,
        hourlyRate: 15.5,
        id: 8,
        name: "Ather 250",
        status: true,
      },
      {
        category: "BIKE",
        description: null,
        hourlyRate: 20.5,
        id: 9,
        name: "Ather 250",
        status: true,
      },
    ],
    totalCount: 9,
  },
  error: null,
  message: "Data fetched Successfully..!!",
  success: true,
}
